version: "3.8"

services:
  app:
    container_name: web-server
    image: ${DOCKER_REPO_NAME}/berich:latest
    environment:
      PROFILE: dev
      TZ: Asia/Seoul
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    logging:
      driver: awslogs
      options:
        awslogs-group: berich-server-log
        awslogs-region: ap-northeast-2
        awslogs-stream: berich-server-${LOG_STREAM_ID}

  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
