FROM openjdk:17-jdk-slim
ARG JAR_FILE=build/libs/app.jar
COPY ${JAR_FILE} app.jar

# 런타임 환경변수 사용을 위해 sh -c 사용
ENTRYPOINT ["sh", "-c", "java -Duser.timezone=Asia/Seoul -Dspring.profiles.active=${PROFILE} -jar /app.jar"]
