spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/berich?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        default_batch_fetch_size: 100
        default_timezone: Asia/Seoul

  # — Kakao Integration (로컬용) —
  kakao:
    client-id: ${KAKAO.CLIENT-ID}
    redirect-uri: ${KAKAO.REDIRECT-URI}

# — JWT Secret Key (로컬용) —
jwt:
  secret: ${JWT.SECRET}
  access-token-validity-in-milliseconds: 3600000
  refresh-token-validity-in-milliseconds: 604800000

# — Logging (로컬용) —
logging:
  level:
    org.hibernate.SQL: debug
    org.example.berichbe: debug
    org.springframework.security: debug

# — Swagger (로컬용) —
springdoc:
  swagger-ui:
    path: /swagger # 스웨거 접근 경로
    groups-order: DESC # API 그룹 표시 순서
    tags-sorter: alpha # 태그 정렬 순서.
    operationsSorter: method # 컨트롤러 정렬 순서
    disable-swagger-default-url: true # swagger-ui default url인 petstore html의 비활성화 설정
    display-request-duration: true
  api-docs:
    path: /api-docs # openAPI 접근 경로. default 값은 /v3/api-docs 이다.
    enabled: true  # 이 옵션이 true로 되어 있어야 Swagger 문서가 생성됨
  show-actuator: true # Spring Actuator의 endpoint까지 보여줄 것인지?
  default-consumes-media-type: application/json # request media type 의 기본 값
  default-produces-media-type: application/json # response media type 의 기본 값
  paths-to-match: /api/** # 해당 패턴에 매칭되는 controller만 swagger-ui에 노출한다.