spring:
  datasource:
    url: jdbc:h2:mem:testdb # ??? ? H2 ??????
    username: sa
    password: password
  h2:
    console:
      enabled: true # H2 ?? ??? (?????? ?????? ?? ??)
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update # ???? DDL ?? (update? ?????? ???? ??)
    show-sql: true # ??? SQL ?? ??